### ISSUE TITLE
Collapse elements do not open after being closed.

### ISSUE THREAD

**Issue by brianteeman** [Joomla3-Admin-template/joomla-cms#36]
On any screen that has an options icon the first time you select it the options open but after clicking options again to close it you can never re-open it

**Comment by mbabker** [comment]
This is an issue for all collapse areas, not just the options one.  Can be duplicated with any of the buttons in Smart Search or the file tree in the Media Manager.

EDIT: Updated the title to be a bit more generic to describe the full issue

**Comment by kyleledbetter** [comment]
Yup, seems like some conflict that only occurs when using Bootstrap jQuery with Mootools. No JS error though...

**Comment by chalak** [comment]
I notice same thing in "user note categories" when clicking on 
Batch process the selected categories

problem in chrome but in firefox it's fine.

**Comment by kyleledbetter** [comment]
This isn't a fix, but we're moving the batch from a collapse to a modal. Still need a global fix for this

**Comment by phproberto** [comment]
The conflict is between bootstrap collapse hide js event and mootools more functions. Is already reported to bootstrap but they don't give support to mootools issues. So isn't going to be fixed in bootstrap.

To avoid this issue in the boostrap plugin for joomla2.5 we work with a patched bootstrap js.

If you are interested I can pull request the patched version or give further details about the issue.

**Comment by phproberto** [comment]
I have sent a pull request with the patched bootstrap JS. 

https://github.com/Joomla3-Admin-template/joomla-cms/pull/93

Now we have to decide if we should avoid to modify/patch the bootstrap files.
